# Generated by Django 3.0.2 on 2020-01-21 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'More Effort'), ('Hard', 'A challenge')], max_length=20)),
                ('ingredients', models.CharField(choices=[('Coffee Granules', 'Coffee Granules'), ('Vanilla', 'Vanilla'), ('Mascarpone', 'Mascarpone'), ('Milk', 'Milk'), ('Sponge fingers', 'Sponge fingers'), ('Mascarpone', 'Mascarpone'), ('Coffee Liqueur', 'Coffee Liqueur'), ('Sugar', 'Sugar'), ('Egg', 'Egg'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Raspberrries', 'Raspberries'), ('Egg Whites', 'Egg Whites'), ('Pistachio', 'Pistachio')], max_length=20)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
