# Generated by Django 3.0.2 on 2020-01-21 10:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='desert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'More Effort'), ('Hard', 'A challenge')], max_length=20)),
                ('ingredients', multiselectfield.db.fields.MultiSelectField(choices=[('Coffee Granules', 'Coffee Granules'), ('Vanilla', 'Vanilla'), ('Mascarpone', 'Mascarpone'), ('Milk', 'Milk'), ('Sponge fingers', 'Sponge fingers'), ('Mascarpone', 'Mascarpone'), ('Coffee Liqueur', 'Coffee Liqueur'), ('Sugar', 'Sugar'), ('Egg', 'Egg'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Raspberrries', 'Raspberries'), ('Egg Whites', 'Egg Whites'), ('Pistachio', 'Pistachio')], max_length=137)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
